fix: jampack again

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,7 +40,18 @@ jobs:
           npm ci
           npm exec -- jampack --nocache ./site
           rm -rf node_modules _jampack .cache
-          
+
       - name: Deploy
         run: |
-          mkdocs gh-deploy --force -f mkdocs.github.yml --dirty
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git checkout --orphan gh-pages
+          if [ ! -d "site" ]; then
+              echo "error: site directory not found"
+              exit 1
+          fi
+          git rm -rf .
+          cp -r site/* .
+          git add .
+          git commit -m "Deploy to GitHub Pages"
+          git push origin gh-pages --force
